// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmSQLn1_RLBs7PbBg-uORo2_5DbCiqrxc',
    appId: '1:547346642036:web:6ebd083449e77a11a6cd21',
    messagingSenderId: '547346642036',
    projectId: 'bitirme-26a4e',
    authDomain: 'bitirme-26a4e.firebaseapp.com',
    storageBucket: 'bitirme-26a4e.firebasestorage.app',
    measurementId: 'G-8TNPGSDFT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznRLHKRDGiWN3j6SFPrsslZb1gq8IwCw',
    appId: '1:547346642036:android:ba7c3cca98642d44a6cd21',
    messagingSenderId: '547346642036',
    projectId: 'bitirme-26a4e',
    storageBucket: 'bitirme-26a4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3yqIehnMvP-DsznFOO8Rbheqq0M3O26w',
    appId: '1:547346642036:ios:d84215f1cbfaf33fa6cd21',
    messagingSenderId: '547346642036',
    projectId: 'bitirme-26a4e',
    storageBucket: 'bitirme-26a4e.firebasestorage.app',
    iosBundleId: 'com.example.ridedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmSQLn1_RLBs7PbBg-uORo2_5DbCiqrxc',
    appId: '1:547346642036:web:4e4ea60d690e1d40a6cd21',
    messagingSenderId: '547346642036',
    projectId: 'bitirme-26a4e',
    authDomain: 'bitirme-26a4e.firebaseapp.com',
    storageBucket: 'bitirme-26a4e.firebasestorage.app',
    measurementId: 'G-FMKE3N8SB3',
  );

}